package com.pixelmonmod.pixelmon.api.enums;

public enum ExperienceGainType {
   BATTLE,
   RARE_CANDY,
   RARE_SODA,
   ULTRA_RARE_SODA,
   EXTRA_SMALL_EXP_CANDY,
   SMALL_EXP_CANDY,
   MEDIUM_EXP_CANDY,
   LARGE_EXP_CANDY,
   EXTRA_LARGE_EXP_CANDY,
   CURRY_KOFFING,
   CURRY_WOBBUFFET,
   CURRY_MILCERY,
   CURRY_COPPERAJAH,
   CURRY_CHARIZARD,
   UNKNOWN;
}
