package com.pixelmonmod.pixelmon.config;

import com.pixelmonmod.pixelmon.enums.items.EnumQuestItems;
import com.pixelmonmod.pixelmon.items.ItemQuest;
import net.minecraft.item.Item;

public class PixelmonItemsQuests {
   public static Item ultraRuinKey;
   public static Item ultraForestKey;
   public static Item ultraDeepSeaKey;
   public static Item amaze_mulch;
   public static Item apricorn_box;
   public static Item aurora_ticket;
   public static Item basement_key_brass;
   public static Item basement_key_silver;
   public static Item berry_bag;
   public static Item berry_pot;
   public static Item bike_voucher;
   public static Item black_mane_hair;
   public static Item boost_mulch;
   public static Item camping_gear;
   public static Item card_key_orange;
   public static Item card_key_red;
   public static Item carrot_seed;
   public static Item common_stone;
   public static Item damp_mulch;
   public static Item dark_stone;
   public static Item devon_scuba_gear;
   public static Item discount_coupon;
   public static Item dragon_skull;
   public static Item elevator_key_flare;
   public static Item endorsement;
   public static Item enigma_stone;
   public static Item eon_flute;
   public static Item eon_ticket;
   public static Item escape_rope;
   public static Item gooey_mulch;
   public static Item growth_mulch;
   public static Item ice_root_carrot;
   public static Item intriguing_stone;
   public static Item legendary_clues;
   public static Item light_stone;
   public static Item lunar_wing;
   public static Item magma_stone;
   public static Item moon_flute;
   public static Item poffin_case;
   public static Item poke_flute;
   public static Item pokeradar;
   public static Item poketchB;
   public static Item poketchR;
   public static Item radiant_petal;
   public static Item red_scale;
   public static Item rich_mulch;
   public static Item shade_root_carrot;
   public static Item spray_duck;
   public static Item squirt_bottle;
   public static Item stable_mulch;
   public static Item sun_flute;
   public static Item surprise_mulch;
   public static Item tm_case;
   public static Item white_mane_hair;
   public static Item wooden_crown;
   public static Item armor_pass;
   public static Item blue_petal;
   public static Item coin_case;
   public static Item crown_pass;
   public static Item devon_scope;
   public static Item fashion_case;
   public static Item forage_bag;
   public static Item gold_teeth;
   public static Item green_petal;
   public static Item hi_tech_earbuds;
   public static Item holo_caster;
   public static Item jade_orb;
   public static Item liberty_pass;
   public static Item max_honey;
   public static Item member_card;
   public static Item mystic_ticket;
   public static Item oaks_letter;
   public static Item oaks_parcel;
   public static Item old_sea_map;
   public static Item orange_petal;
   public static Item pink_petal;
   public static Item pokeblock_case;
   public static Item professors_mask;
   public static Item prop_case;
   public static Item purple_petal;
   public static Item rainbow_flower;
   public static Item rainbow_pass;
   public static Item red_petal;
   public static Item ride_pager;
   public static Item seal_case;
   public static Item secret_key;
   public static Item silph_scope;
   public static Item sonias_book;
   public static Item sparkling_stone;
   public static Item ss_ticket;
   public static Item style_card;
   public static Item tri_pass;
   public static Item yellow_petal;
   public static Item z_power_ring;
   public static Item z_ring;

   public static void load() {
      ultraRuinKey = new ItemQuest(EnumQuestItems.Ultra_Ruin_Key, 1);
      ultraForestKey = new ItemQuest(EnumQuestItems.Ultra_Forest_Key, 1);
      ultraDeepSeaKey = new ItemQuest(EnumQuestItems.Ultra_Deep_Sea_Key, 1);
      amaze_mulch = new ItemQuest(EnumQuestItems.Amaze_Mulch, 16);
      apricorn_box = new ItemQuest(EnumQuestItems.Apricorn_Box, 1);
      aurora_ticket = new ItemQuest(EnumQuestItems.Aurora_Ticket, 1);
      basement_key_brass = new ItemQuest(EnumQuestItems.Basement_Key_Brass, 1);
      basement_key_silver = new ItemQuest(EnumQuestItems.Basement_Key_Silver, 1);
      berry_bag = new ItemQuest(EnumQuestItems.Berry_Bag, 1);
      berry_pot = new ItemQuest(EnumQuestItems.Berry_Pot, 1);
      bike_voucher = new ItemQuest(EnumQuestItems.Bike_Voucher, 16);
      black_mane_hair = new ItemQuest(EnumQuestItems.Black_Mane_Hair, 1);
      boost_mulch = new ItemQuest(EnumQuestItems.Boost_Mulch, 16);
      camping_gear = new ItemQuest(EnumQuestItems.Camping_Gear, 1);
      card_key_orange = new ItemQuest(EnumQuestItems.Card_Key_Orange, 1);
      card_key_red = new ItemQuest(EnumQuestItems.Card_Key_Red, 1);
      carrot_seed = new ItemQuest(EnumQuestItems.Carrot_Seed, 16);
      common_stone = new ItemQuest(EnumQuestItems.Common_Stone, 64);
      damp_mulch = new ItemQuest(EnumQuestItems.Damp_Mulch, 16);
      dark_stone = new ItemQuest(EnumQuestItems.Dark_Stone, 1);
      devon_scuba_gear = new ItemQuest(EnumQuestItems.Devon_Scuba_Gear, 1);
      discount_coupon = new ItemQuest(EnumQuestItems.Discount_Coupon, 16);
      dragon_skull = new ItemQuest(EnumQuestItems.Dragon_Skull, 1);
      elevator_key_flare = new ItemQuest(EnumQuestItems.Elevator_Key_Flare, 1);
      endorsement = new ItemQuest(EnumQuestItems.Endorsement, 1);
      enigma_stone = new ItemQuest(EnumQuestItems.Enigma_Stone, 1);
      eon_flute = new ItemQuest(EnumQuestItems.Eon_Flute, 1);
      eon_ticket = new ItemQuest(EnumQuestItems.Eon_Ticket, 1);
      escape_rope = new ItemQuest(EnumQuestItems.Escape_Rope, 16);
      gooey_mulch = new ItemQuest(EnumQuestItems.Gooey_Mulch, 16);
      growth_mulch = new ItemQuest(EnumQuestItems.Growth_Mulch, 16);
      ice_root_carrot = new ItemQuest(EnumQuestItems.Ice_Root_Carrot, 1);
      intriguing_stone = new ItemQuest(EnumQuestItems.Intriguing_Stone, 1);
      legendary_clues = new ItemQuest(EnumQuestItems.Legendary_Clues, 1);
      light_stone = new ItemQuest(EnumQuestItems.Light_Stone, 1);
      lunar_wing = new ItemQuest(EnumQuestItems.Lunar_Wing, 1);
      magma_stone = new ItemQuest(EnumQuestItems.Magma_Stone, 1);
      moon_flute = new ItemQuest(EnumQuestItems.Moon_Flute, 1);
      poffin_case = new ItemQuest(EnumQuestItems.Poffin_Case, 1);
      poke_flute = new ItemQuest(EnumQuestItems.Poke_Flute, 1);
      pokeradar = new ItemQuest(EnumQuestItems.Pokeradar, 1);
      poketchB = new ItemQuest(EnumQuestItems.PoketchB, 1);
      poketchR = new ItemQuest(EnumQuestItems.PoketchR, 1);
      radiant_petal = new ItemQuest(EnumQuestItems.Radiant_Petal, 16);
      red_scale = new ItemQuest(EnumQuestItems.Red_Scale, 16);
      rich_mulch = new ItemQuest(EnumQuestItems.Rich_Mulch, 16);
      shade_root_carrot = new ItemQuest(EnumQuestItems.Shade_Root_Carrot, 1);
      spray_duck = new ItemQuest(EnumQuestItems.Spray_Duck, 1);
      squirt_bottle = new ItemQuest(EnumQuestItems.Squirt_Bottle, 1);
      stable_mulch = new ItemQuest(EnumQuestItems.Stable_Mulch, 16);
      sun_flute = new ItemQuest(EnumQuestItems.Sun_Flute, 1);
      surprise_mulch = new ItemQuest(EnumQuestItems.Surprise_Mulch, 16);
      tm_case = new ItemQuest(EnumQuestItems.TM_Case, 1);
      white_mane_hair = new ItemQuest(EnumQuestItems.White_Mane_Hair, 1);
      wooden_crown = new ItemQuest(EnumQuestItems.Wooden_Crown, 1);
      armor_pass = new ItemQuest(EnumQuestItems.Armor_Pass, 1);
      blue_petal = new ItemQuest(EnumQuestItems.Blue_Petal, 16);
      coin_case = new ItemQuest(EnumQuestItems.Coin_Case, 1);
      crown_pass = new ItemQuest(EnumQuestItems.Crown_Pass, 1);
      devon_scope = new ItemQuest(EnumQuestItems.Devon_Scope, 1);
      fashion_case = new ItemQuest(EnumQuestItems.Fashion_Case, 1);
      forage_bag = new ItemQuest(EnumQuestItems.Forage_Bag, 1);
      gold_teeth = new ItemQuest(EnumQuestItems.Gold_Teeth, 16);
      green_petal = new ItemQuest(EnumQuestItems.Green_Petal, 16);
      hi_tech_earbuds = new ItemQuest(EnumQuestItems.Hi_Tech_Earbuds, 1);
      holo_caster = new ItemQuest(EnumQuestItems.Holo_Caster, 1);
      jade_orb = new ItemQuest(EnumQuestItems.Jade_Orb, 64);
      liberty_pass = new ItemQuest(EnumQuestItems.Liberty_Pass, 1);
      max_honey = new ItemQuest(EnumQuestItems.Max_Honey, 64);
      member_card = new ItemQuest(EnumQuestItems.Member_Card, 1);
      mystic_ticket = new ItemQuest(EnumQuestItems.Mystic_Ticket, 1);
      oaks_letter = new ItemQuest(EnumQuestItems.Oaks_Letter, 1);
      oaks_parcel = new ItemQuest(EnumQuestItems.Oaks_Parcel, 1);
      old_sea_map = new ItemQuest(EnumQuestItems.Old_Sea_Map, 1);
      orange_petal = new ItemQuest(EnumQuestItems.Orange_Petal, 16);
      pink_petal = new ItemQuest(EnumQuestItems.Pink_Petal, 16);
      pokeblock_case = new ItemQuest(EnumQuestItems.Pokeblock_Case, 1);
      professors_mask = new ItemQuest(EnumQuestItems.Professors_Mask, 1);
      prop_case = new ItemQuest(EnumQuestItems.Prop_Case, 1);
      purple_petal = new ItemQuest(EnumQuestItems.Purple_Petal, 16);
      rainbow_flower = new ItemQuest(EnumQuestItems.Rainbow_Flower, 16);
      rainbow_pass = new ItemQuest(EnumQuestItems.Rainbow_Pass, 1);
      red_petal = new ItemQuest(EnumQuestItems.Red_Petal, 16);
      ride_pager = new ItemQuest(EnumQuestItems.Ride_Pager, 1);
      seal_case = new ItemQuest(EnumQuestItems.Seal_Case, 1);
      secret_key = new ItemQuest(EnumQuestItems.Secret_Key, 1);
      silph_scope = new ItemQuest(EnumQuestItems.Silph_Scope, 1);
      sonias_book = new ItemQuest(EnumQuestItems.Sonias_Book, 1);
      sparkling_stone = new ItemQuest(EnumQuestItems.Sparkling_Stone, 1);
      ss_ticket = new ItemQuest(EnumQuestItems.SS_Ticket, 1);
      style_card = new ItemQuest(EnumQuestItems.Style_Card, 1);
      tri_pass = new ItemQuest(EnumQuestItems.Tri_Pass, 1);
      yellow_petal = new ItemQuest(EnumQuestItems.Yellow_Petal, 16);
      z_power_ring = new ItemQuest(EnumQuestItems.Z_Power_Ring, 1);
      z_ring = new ItemQuest(EnumQuestItems.Z_Ring, 1);
   }
}
