package com.pixelmonmod.pixelmon.config;

import com.pixelmonmod.pixelmon.blocks.spawning.TileEntityPixelmonSpawner;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityAnvil;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityApricornTree;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityArmchair;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityBell;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityBerryTree;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityBoulder;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityBox;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityCashRegister;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityChair;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityClock;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityCloningMachine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityClothedTable;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityCookingPot;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityCushionChair;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityDecorativeBase;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityEndTable;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityEvolutionRock;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityFoldingChair;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityFossilCleaner;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityFossilDisplay;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityFossilMachine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityFridge;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityGracidea;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityGymSign;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityHealer;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityIlexShrine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityInfuser;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityMechanicalAnvil;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityMultiCouch;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityMusicBlock;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityOrb;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityPC;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityPicketFenceNormal;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityPlateHolder;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityPokeChest;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityPokegift;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRug;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityScroll;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityShrine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTV;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTV3;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTemporaryLight;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTimespaceAltar;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTradeMachine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTrashcan;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityTree;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityUmbrella;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityVendingMachine;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityWarpPlate;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityWaterFloat;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityZygardeAssembly;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityZygardeCell;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileFan;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileMower;
import com.pixelmonmod.pixelmon.blocks.tileEntities.TileWashingMachine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.FoldingChairRenderer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.FossilDisplayRenderer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.GenericSmdRenderer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.GymSignRenderer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityAnvil;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityApricornTrees;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityBell;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityBerryTree;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityCloningMachine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityCookingPot;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityDecorativeBase;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityEvolutionRock;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityHealer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityInfuser;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityMechanicalAnvil;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityOrb;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityPicketFence;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityPlateHolder;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityPokeChest;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityPokeGift;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityRanch;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityScroll;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityShrine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityTimespaceShrine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityTradingMachine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityZygardeAssembly;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileEntityZygardeCell;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileFossilCleaner;
import com.pixelmonmod.pixelmon.client.render.tileEntities.RenderTileFossilMachine;
import com.pixelmonmod.pixelmon.client.render.tileEntities.TVRenderer;
import com.pixelmonmod.pixelmon.client.render.tileEntities.TreeRenderer;
import java.util.Map;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.datafix.fixes.TileEntityId;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.ObfuscationReflectionHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class TileEntityRegistry {
   static void registerTileEntities() {
      String prefix = "pixelmon:";
      TileEntity.func_190560_a(prefix + "pc", TileEntityPC.class);
      TileEntity.func_190560_a(prefix + "anvil", TileEntityAnvil.class);
      TileEntity.func_190560_a(prefix + "ranch_block", TileEntityRanchBlock.class);
      TileEntity.func_190560_a(prefix + "healer", TileEntityHealer.class);
      TileEntity.func_190560_a(prefix + "mechanical_anvil", TileEntityMechanicalAnvil.class);
      TileEntity.func_190560_a(prefix + "compressor", TileEntityInfuser.class);
      TileEntity.func_190560_a(prefix + "cookingpot", TileEntityCookingPot.class);
      TileEntity.func_190560_a(prefix + "fossil_machine", TileEntityFossilMachine.class);
      TileEntity.func_190560_a(prefix + "trade_machine", TileEntityTradeMachine.class);
      TileEntity.func_190560_a(prefix + "fossil_cleaner", TileEntityFossilCleaner.class);
      TileEntity.func_190560_a(prefix + "evolution_rock", TileEntityEvolutionRock.class);
      TileEntity.func_190560_a(prefix + "pixelmon_spawner", TileEntityPixelmonSpawner.class);
      TileEntity.func_190560_a(prefix + "bird_shrine", TileEntityShrine.class);
      TileEntity.func_190560_a(prefix + "timespace_shrine", TileEntityTimespaceAltar.class);
      TileEntity.func_190560_a(prefix + "ilex_shrine", TileEntityIlexShrine.class);
      TileEntity.func_190560_a(prefix + "plate_holder", TileEntityPlateHolder.class);
      TileEntity.func_190560_a(prefix + "bell", TileEntityBell.class);
      TileEntity.func_190560_a(prefix + "decorative", TileEntityDecorativeBase.class);
      TileEntity.func_190560_a(prefix + "poke_chest", TileEntityPokeChest.class);
      TileEntity.func_190560_a(prefix + "cloning_machine", TileEntityCloningMachine.class);
      TileEntity.func_190560_a(prefix + "warp_plate", TileEntityWarpPlate.class);
      TileEntity.func_190560_a(prefix + "berry_tree", TileEntityBerryTree.class);
      TileEntity.func_190560_a(prefix + "apricorn_tree", TileEntityApricornTree.class);
      TileEntity.func_190560_a(prefix + "gracidea", TileEntityGracidea.class);
      TileEntity.func_190560_a(prefix + "decorative_tree", TileEntityTree.class);
      TileEntity.func_190560_a(prefix + "decorative_bolder", TileEntityBoulder.class);
      TileEntity.func_190560_a(prefix + "box", TileEntityBox.class);
      TileEntity.func_190560_a(prefix + "clothed_table", TileEntityClothedTable.class);
      TileEntity.func_190560_a(prefix + "trashcan", TileEntityTrashcan.class);
      TileEntity.func_190560_a(prefix + "gym_sign", TileEntityGymSign.class);
      TileEntity.func_190560_a(prefix + "tv", TileEntityTV.class);
      TileEntity.func_190560_a(prefix + "tv3", TileEntityTV3.class);
      TileEntity.func_190560_a(prefix + "chair", TileEntityChair.class);
      TileEntity.func_190560_a(prefix + "armchair", TileEntityArmchair.class);
      TileEntity.func_190560_a(prefix + "cashregister", TileEntityCashRegister.class);
      TileEntity.func_190560_a(prefix + "fossil_display", TileEntityFossilDisplay.class);
      TileEntity.func_190560_a(prefix + "end_table", TileEntityEndTable.class);
      TileEntity.func_190560_a(prefix + "temporary_light", TileEntityTemporaryLight.class);
      TileEntity.func_190560_a(prefix + "picket_fence", TileEntityPicketFenceNormal.class);
      TileEntity.func_190560_a(prefix + "green_folding_chair", TileEntityFoldingChair.class);
      TileEntity.func_190560_a(prefix + "poke_gift", TileEntityPokegift.class);
      TileEntity.func_190560_a(prefix + "cushion_chair", TileEntityCushionChair.class);
      TileEntity.func_190560_a(prefix + "clock", TileEntityClock.class);
      TileEntity.func_190560_a(prefix + "rug", TileEntityRug.class);
      TileEntity.func_190560_a(prefix + "umbrella", TileEntityUmbrella.class);
      TileEntity.func_190560_a(prefix + "vending_machine", TileEntityVendingMachine.class);
      TileEntity.func_190560_a(prefix + "fridge", TileEntityFridge.class);
      TileEntity.func_190560_a(prefix + "water_float", TileEntityWaterFloat.class);
      TileEntity.func_190560_a(prefix + "couch", TileEntityMultiCouch.class);
      TileEntity.func_190560_a(prefix + "orb", TileEntityOrb.class);
      TileEntity.func_190560_a(prefix + "mower", TileMower.class);
      TileEntity.func_190560_a(prefix + "washing_machine", TileWashingMachine.class);
      TileEntity.func_190560_a(prefix + "fan", TileFan.class);
      TileEntity.func_190560_a(prefix + "reassembly_unit", TileEntityZygardeAssembly.class);
      TileEntity.func_190560_a(prefix + "zygard_cell", TileEntityZygardeCell.class);
      TileEntity.func_190560_a(prefix + "scroll", TileEntityScroll.class);
      TileEntity.func_190560_a(prefix + "music_block", TileEntityMusicBlock.class);
      remap();
   }

   @SideOnly(Side.CLIENT)
   public static void registerRenderers() {
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPC.class, (new GenericSmdRenderer("blocks/computer/computer.pqc", (String)null)).setCorrectionAngles(180));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityAnvil.class, new RenderTileEntityAnvil());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHealer.class, new RenderTileEntityHealer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityShrine.class, new RenderTileEntityShrine());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityIlexShrine.class, (new GenericSmdRenderer("blocks/shrines/ilex_shrine.pqc", "shrines/ilex.png")).rotate(-90.0F, 1.0F, 0.0F, 0.0F).scale(0.25F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTimespaceAltar.class, new RenderTileEntityTimespaceShrine());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPlateHolder.class, new RenderTileEntityPlateHolder());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBell.class, new RenderTileEntityBell());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPokeChest.class, new RenderTileEntityPokeChest());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBerryTree.class, new RenderTileEntityBerryTree());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRanchBlock.class, new RenderTileEntityRanch());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityApricornTree.class, new RenderTileEntityApricornTrees());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTradeMachine.class, new RenderTileEntityTradingMachine());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFossilMachine.class, new RenderTileFossilMachine());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFossilCleaner.class, new RenderTileFossilCleaner());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityEvolutionRock.class, new RenderTileEntityEvolutionRock());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCloningMachine.class, new RenderTileEntityCloningMachine());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityDecorativeBase.class, new RenderTileEntityDecorativeBase());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityMechanicalAnvil.class, new RenderTileEntityMechanicalAnvil());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityInfuser.class, new RenderTileEntityInfuser());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCookingPot.class, new RenderTileEntityCookingPot());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGracidea.class, (new GenericSmdRenderer("blocks/gracidea/gracidea.pqc", "gracidea.png")).rotate(-90.0F, 1.0F, 0.0F, 0.0F).scale(0.1F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOrb.class, new RenderTileEntityOrb());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTV.class, new TVRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTV3.class, (new GenericSmdRenderer("pixelutilities/tv/tv.pqc", "tv3.png")).scale(0.075F).setCorrectionAngles(90).rotate(-90.0F, 1.0F, 0.0F, 0.0F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTree.class, new TreeRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGymSign.class, new GymSignRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPokegift.class, new RenderTileEntityPokeGift());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFossilDisplay.class, new FossilDisplayRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPicketFenceNormal.class, new RenderTileEntityPicketFence());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFoldingChair.class, new FoldingChairRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBoulder.class, new GenericSmdRenderer("pixelutilities/Bolder/Bolder.pqc", "BolderModel.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBox.class, (new GenericSmdRenderer("pixelutilities/Box/Box.pqc", "BoxModel.png")).disableCulling());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityClothedTable.class, new GenericSmdRenderer("pixelutilities/ClothedTable/clothedtable.pqc", "ClothedTableModel.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityChair.class, new GenericSmdRenderer("pixelutilities/chair/chair.pqc", (String)null));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityArmchair.class, (new GenericSmdRenderer("pixelutilities/armchair/armchair.pqc", (String)null)).scale(0.1F).setCorrectionAngles(180).rotate(-90.0F, 1.0F, 0.0F, 0.0F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCashRegister.class, (new GenericSmdRenderer("pixelutilities/cashregister/cashregister.pqc", "cashregister.png")).scale(0.075F).setCorrectionAngles(-90).rotate(-90.0F, 1.0F, 0.0F, 0.0F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrashcan.class, new GenericSmdRenderer("pixelutilities/TrashCan/TrashCan.pqc", "TrashcanModel.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFridge.class, (new GenericSmdRenderer("pixelutilities/Fridge/fridge.pqc", "FridgeModel.png")).disableCulling().setCorrectionAngles(180));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityEndTable.class, new GenericSmdRenderer("pixelutilities/EndTable/EndTable.pqc", "EndTableModel.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWaterFloat.class, (new GenericSmdRenderer("pixelutilities/WaterFloat/WaterFloat.pqc", (String)null)).setCorrectionAngles(90).setYOffset(0.2F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityMultiCouch.class, (new GenericSmdRenderer("pixelutilities/couch/couch.pqc", (String)null)).scale(0.1F).rotate(-90.0F, 1.0F, 0.0F, 0.0F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRug.class, (new GenericSmdRenderer("pixelutilities/Rug/Rug.pqc", (String)null)).setCorrectionAngles(90).setYOffset(0.06F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityUmbrella.class, new GenericSmdRenderer("pixelutilities/umbrella/Umbrella.pqc", (String)null));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCushionChair.class, new GenericSmdRenderer("pixelutilities/CushionChair/CushionChair.pqc", (String)null));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityClock.class, new GenericSmdRenderer("pixelutilities/Clock/Clock.pqc", (String)null));
      ClientRegistry.bindTileEntitySpecialRenderer(TileFan.class, new GenericSmdRenderer("blocks/machines/fan.pqc", "fan.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileWashingMachine.class, new GenericSmdRenderer("blocks/machines/washingmachine.pqc", "washingmachine.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileMower.class, new GenericSmdRenderer("blocks/machines/mower.pqc", "mower.png"));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityZygardeAssembly.class, new RenderTileEntityZygardeAssembly());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityZygardeCell.class, new RenderTileEntityZygardeCell());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityScroll.class, new RenderTileEntityScroll());
   }

   private static void remap() {
      Map remap = (Map)ObfuscationReflectionHelper.getPrivateValue(TileEntityId.class, (Object)null, 0);
      remap.put("Pokemon PC", "pixelmon:pc");
      remap.put("Anvil", "pixelmon:anvil");
      remap.put("Ranch Block", "pixelmon:ranch_block");
      remap.put("Healer", "pixelmon:healer");
      remap.put("MechanicalAnvilTE", "pixelmon:mechanical_anvil");
      remap.put("Fossil Machine", "pixelmon:fossil_machine");
      remap.put("Trade Machine", "pixelmon:trade_machine");
      remap.put("SolarPanel", "pixelmon:solar_panel");
      remap.put("Wire", "pixelmon:wire");
      remap.put("PokeDoll", "pixelmon:poke_doll");
      remap.put("Electric Furnace", "pixelmon:electric_furnace");
      remap.put("Mower", "pixelmon:mower");
      remap.put("Washing Machine", "pixelmon:washing_machine");
      remap.put("Fan", "pixelmon:fan");
      remap.put("Battery", "pixelmon:battery");
      remap.put("Fossil Cleaner", "pixelmon:fossil_cleaner");
      remap.put("Evolution Rock", "pixelmon:evolution_rock");
      remap.put("Pixelmon Spawner", "pixelmon:pixelmon_spawner");
      remap.put("Bird Shrine", "pixelmon:bird_shrine");
      remap.put("Decorative Tileent", "pixelmon:decorative");
      remap.put("entityPokeChest", "pixelmon:poke_chest");
      remap.put("Cloning Machine", "pixelmon:cloning_machine");
      remap.put("Warp Plate", "pixelmon:warp_plate");
      remap.put("BerryTree", "pixelmon:berry_tree");
      remap.put("Apricorn Tree", "pixelmon:apricorn_tree");
      remap.put("TreeEntity", "pixelmon:decorative_tree");
      remap.put("BolderEntity", "pixelmon:decorative_bolder");
      remap.put("BoxEntity", "pixelmon:box");
      remap.put("ClothedTableEntity", "pixelmon:clothed_table");
      remap.put("TrashcanEntity", "pixelmon:trashcan");
      remap.put("GymSignEntity", "pixelmon:gym_sign");
      remap.put("TVEntity", "pixelmon:tv");
      remap.put("ChairEntity", "pixelmon:chair");
      remap.put("FossilDisplayEntity", "pixelmon:fossil_display");
      remap.put("EndTableEntity", "pixelmon:end_table");
      remap.put("PicketFenceNormalEntity", "pixelmon:picket_fence");
      remap.put("GreenFoldingChairEntity", "pixelmon:green_folding_chair");
      remap.put("PokegiftEntity", "pixelmon:poke_gift");
      remap.put("CushionChairEntity", "pixelmon:cushion_chair");
      remap.put("ClockEntity", "pixelmon:clock");
      remap.put("RugEntity", "pixelmon:rug");
      remap.put("UmbrellaEntity", "pixelmon:umbrella");
      remap.put("VendingMachineEntity", "pixelmon:vending_machine");
      remap.put("FridgeEntity", "pixelmon:fridge");
      remap.put("WaterFloatEntity", "pixelmon:water_float");
      remap.put("RedCushionChairEntity", "pixelmon:cushion_chair");
      remap.put("YellowCushionChairEntity", "pixelmon:cushion_chair");
      remap.put("BlueClockEntity", "pixelmon:clock");
      remap.put("PinkClockEntity", "pixelmon:clock");
      remap.put("RedRugEntity", "pixelmon:rug");
      remap.put("BlueRugEntity", "pixelmon:rug");
      remap.put("GreenRugEntity", "pixelmon:rug");
      remap.put("YellowRugEntity", "pixelmon:rug");
      remap.put("RedUmbrellaEntity", "pixelmon:umbrella");
      remap.put("BlueUmbrellaEntity", "pixelmon:umbrella");
      remap.put("GreenUmbrellaEntity", "pixelmon:umbrella");
      remap.put("YellowUmbrellaEntity", "pixelmon:umbrella");
      remap.put("RedVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("PinkVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("BlueVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("GreenVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("OrangeVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("YellowVendingMachineEntity", "pixelmon:vending_machine");
      remap.put("RedWaterFloatEntity", "pixelmon:water_float");
      remap.put("BlueWaterFloatEntity", "pixelmon:water_float");
      remap.put("PinkWaterFloatEntity", "pixelmon:water_float");
      remap.put("PurpleWaterFloatEntity", "pixelmon:water_float");
      remap.put("OrangeWaterFloatEntity", "pixelmon:water_float");
      remap.put("YellowWaterFloatEntity", "pixelmon:water_float");
   }
}
