package com.pixelmonmod.tcg.gui;

import net.minecraft.util.ResourceLocation;

public class TCGResources {
   public static final String PREFIX = "tcg";
   public static final ResourceLocation BASE = new ResourceLocation("tcg:gui/cards/base.png");
   public static final ResourceLocation ENERGY_FIRE = new ResourceLocation("tcg:gui/cards/icons/icons_circle_fire.png");
   public static final ResourceLocation ENERGY_WATER = new ResourceLocation("tcg:gui/cards/icons/icons_circle_water.png");
   public static final ResourceLocation ENERGY_GRASS = new ResourceLocation("tcg:gui/cards/icons/icons_circle_grass.png");
   public static final ResourceLocation ENERGY_LIGHTNING = new ResourceLocation("tcg:gui/cards/icons/icons_circle_lightning.png");
   public static final ResourceLocation ENERGY_FIGHTING = new ResourceLocation("tcg:gui/cards/icons/icons_circle_fighting.png");
   public static final ResourceLocation ENERGY_PSYCHIC = new ResourceLocation("tcg:gui/cards/icons/icons_circle_psychic.png");
   public static final ResourceLocation ENERGY_COLORLESS = new ResourceLocation("tcg:gui/cards/icons/icons_circle_colorless.png");
   public static final ResourceLocation ENERGY_DARKNESS = new ResourceLocation("tcg:gui/cards/icons/icons_circle_darkness.png");
   public static final ResourceLocation ENERGY_METAL = new ResourceLocation("tcg:gui/cards/icons/icons_circle_metal.png");
   public static final ResourceLocation ENERGY_DRAGON = new ResourceLocation("tcg:gui/cards/icons/icons_circle_dragon.png");
   public static final ResourceLocation ENERGY_FAIRY = new ResourceLocation("tcg:gui/cards/icons/icons_circle_fairy.png");
   public static final ResourceLocation ENERGY_RAINBOW = new ResourceLocation("tcg:gui/cards/icons/icons_circle_rainbow.png");
   public static final ResourceLocation ENERGY_NONE = new ResourceLocation("tcg:gui/cards/icons/icons_circle_none.png");
   public static final ResourceLocation ENERGY_FIRE_HD = new ResourceLocation("tcg:gui/cards/icons/fire.png");
   public static final ResourceLocation ENERGY_WATER_HD = new ResourceLocation("tcg:gui/cards/icons/water.png");
   public static final ResourceLocation ENERGY_GRASS_HD = new ResourceLocation("tcg:gui/cards/icons/grass.png");
   public static final ResourceLocation ENERGY_LIGHTNING_HD = new ResourceLocation("tcg:gui/cards/icons/lightning.png");
   public static final ResourceLocation ENERGY_FIGHTING_HD = new ResourceLocation("tcg:gui/cards/icons/fighting.png");
   public static final ResourceLocation ENERGY_PSYCHIC_HD = new ResourceLocation("tcg:gui/cards/icons/psychic.png");
   public static final ResourceLocation ENERGY_COLORLESS_HD = new ResourceLocation("tcg:gui/cards/icons/colorless.png");
   public static final ResourceLocation ENERGY_DARKNESS_HD = new ResourceLocation("tcg:gui/cards/icons/darkness.png");
   public static final ResourceLocation ENERGY_METAL_HD = new ResourceLocation("tcg:gui/cards/icons/metal.png");
   public static final ResourceLocation ENERGY_DRAGON_HD = new ResourceLocation("tcg:gui/cards/icons/dragon.png");
   public static final ResourceLocation ENERGY_FAIRY_HD = new ResourceLocation("tcg:gui/cards/icons/fairy.png");
   public static final ResourceLocation ENERGY_RAINBOW_HD = new ResourceLocation("tcg:gui/cards/icons/rainbow.png");
   public static final ResourceLocation ENERGY_FIRE_HDA = new ResourceLocation("tcg:gui/cards/icons/fireA.png");
   public static final ResourceLocation ENERGY_WATER_HDA = new ResourceLocation("tcg:gui/cards/icons/waterA.png");
   public static final ResourceLocation ENERGY_GRASS_HDA = new ResourceLocation("tcg:gui/cards/icons/grassA.png");
   public static final ResourceLocation ENERGY_LIGHTNING_HDA = new ResourceLocation("tcg:gui/cards/icons/lightningA.png");
   public static final ResourceLocation ENERGY_FIGHTING_HDA = new ResourceLocation("tcg:gui/cards/icons/fightingA.png");
   public static final ResourceLocation ENERGY_PSYCHIC_HDA = new ResourceLocation("tcg:gui/cards/icons/psychicA.png");
   public static final ResourceLocation ENERGY_COLORLESS_HDA = new ResourceLocation("tcg:gui/cards/icons/colorlessA.png");
   public static final ResourceLocation ENERGY_DARKNESS_HDA = new ResourceLocation("tcg:gui/cards/icons/darknessA.png");
   public static final ResourceLocation ENERGY_METAL_HDA = new ResourceLocation("tcg:gui/cards/icons/metalA.png");
   public static final ResourceLocation ENERGY_DRAGON_HDA = new ResourceLocation("tcg:gui/cards/icons/dragonA.png");
   public static final ResourceLocation ENERGY_FAIRY_HDA = new ResourceLocation("tcg:gui/cards/icons/fairyA.png");
   public static final ResourceLocation ENERGY_RAINBOW_HDA = new ResourceLocation("tcg:gui/cards/icons/rainbowA.png");
   public static final ResourceLocation STAGE_BASIC = new ResourceLocation("tcg:gui/cards/icons/basic.png");
   public static final ResourceLocation STAGE_ONE = new ResourceLocation("tcg:gui/cards/icons/stage1.png");
   public static final ResourceLocation STAGE_TWO = new ResourceLocation("tcg:gui/cards/icons/stage2.png");
   public static final ResourceLocation STAGE_MEGA = new ResourceLocation("tcg:gui/cards/icons/mega.png");
   public static final ResourceLocation FOSSIL = new ResourceLocation("tcg", "gui/cards/foreground/fossil.png");
}
